[generator] add country signing
Signed-off-by: zyphlar <zyphlar@gmail.com>

diff --git a/.forgejo/workflows/map-generator.yml b/.forgejo/workflows/map-generator.yml
--- a/.forgejo/workflows/map-generator.yml
+++ b/.forgejo/workflows/map-generator.yml
@@ -490,6 +490,7 @@ jobs:
       volumes:
         - /mnt/4tbexternal/:/mnt/4tbexternal/
         - /mnt/4tbexternal/osm-planet:/home/planet
+        - /root/keys:~/keys
       options: --ulimit nofile=262144:262144
     concurrency:
       group: ${{ github.workflow }}-map-generator-${{ github.event.pull_request.number || github.ref }}
@@ -518,6 +519,18 @@ jobs:
         run: |
           cd ~/comaps
           bash ./tools/unix/maps/docker_maps_generator.sh
+      - name: Sign countries.txt and copy to latest
+        shell: bash
+        run: |
+          shopt -s nullglob
+          buildfolder=$(find /mnt/4tbexternal/osm-maps/ -mindepth 1 -maxdepth 1 -iname "2*" -type d | sort -n -r | head -1 | cut -d/ -f5)
+          builddate=$(find /mnt/4tbexternal/osm-maps/*/ -mindepth 1 -maxdepth 1 -iname "2*" -type d | sort -n -r | head -1 | cut -d/ -f6)
+          cd /mnt/4tbexternal/osm-maps/$buildfolder/$builddate
+          openssl pkeyutl -sign -inkey ~/keys/countries_ed25519_sk.pem -rawin -in countries.txt -out countries.txt.sig
+          openssl pkeyutl -verify -pubin -inkey ~/keys/countries_ed25519_pk.pem -rawin -in countries.txt -sigfile countries.txt.sig
+          cd ..
+          mkdir -p latest
+          cp -p /mnt/4tbexternal/osm-maps/$buildfolder/$builddate/countries* latest
       - name: Notify Zulip
         run: |
           curl -X POST https://comaps.zulipchat.com/api/v1/messages \
@@ -565,6 +578,23 @@ jobs:
             echo "<$(date +%T)> No MWM files in /mnt/4tbexternal/osm-maps/$buildfolder/$builddate/*.mwm, not uploading maps."
             echo "<$(date +%T)> Found top level: $(ls -alt /mnt/4tbexternal/osm-maps/*)"
             echo "<$(date +%T)> Found second level: $(ls -alt /mnt/4tbexternal/osm-maps/$buildfolder/*)"
+          fi
+
+          # the /latest folder is newly created each build, but it may not have succeeded...
+          buildpath=/mnt/4tbexternal/osm-maps/$buildfolder/latest
+          countriesfiles=( $buildpath/countries* )
+          if (( ${#countriesfiles[@]} > 1 )); then
+            openssl pkeyutl -verify -pubin -inkey ~/keys/countries_ed25519_pk.pem -rawin -in $buildpath/countries.txt -sigfile $buildpath/countries.txt.sig
+            verify=$?
+            if [[ $verify == 0 ]]; then
+              echo "<$(date +%T)> Uploading countries.txt & .sig from $buildpath..."
+              ./upload_to_cdn.sh $buildpath
+            else
+              echo "<$(date +%T)> Failed verifying countries.txt.sig: openssl verify returned $verify"
+            fi
+          else
+            echo "<$(date +%T)> ERROR: Didn't find countries.txt & .sig in $buildpath: [$countriesfiles]"
+            exit 1
           fi
       - name: Notify Zulip
         run: |
